In [1]:
#              TEAM ID:PNT2022TMID04381
#              737819CSR112-ASSIGNMENT-1

#              BASIC PYTHON


['Hi', 'iam', 'priyanka']


In [28]:
# 1.SPLIT THE STRING

s="Hi iam priyanka"
print(s.split())

['Hi', 'iam', 'priyanka']


In [29]:
# 2.USING .FORMAT TO PRINT THE STRING

planet="Earth"
diameter=345627
txt="The diameter of {name} is {dia} kilometers.".format(name=planet,dia=diameter)
print(txt)

The diameter of Earth is 345627 kilometers.


In [30]:
# 3.IN THIS NEXT DICTIONARY GRAB THE WORD 'RESULT'

store={'A':[0,1,2,{'text':['yes','no','hi',{'target':[4,5,6,'result']}]}]}
print(store['A'][3]["text"][3]['target'][3])


result


In [8]:
#IMPORT NUMPY

import numpy as np

In [31]:
# 4.1 ARRAY OF 10 ZEROS 

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# 4.2 ARRAY OF 10 FIVES

np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
# 5.CREATE AN ARRAY OF ALL EVEN INTEGERS (10-50)

print(np.arange(10,50,2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [19]:
# 6.CREATE 5*5 VALUES RANGE FROM 0 TO 25

np.arange(0,25).reshape((5,5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
# 7.CONCATENATE A AND B ARRAY

a=np.array([11,12,13,14,15])
b=np.array([22,23,24,25,26])
res=np.concatenate((a,b))
print (res)

[11 12 13 14 15 22 23 24 25 26]


In [22]:
# 8.CREATE A DATAFRAME WITH 4 ROWS AND 2 COLS

import pandas as pd
a={'c1':[1,2,3,4],'c2':[5,6,7,8]}
df=pd.DataFrame(a)
print(df)


   c1  c2
0   1   5
1   2   6
2   3   7
3   4   8


In [24]:
# 9.GENERATE THE SERIES OF DATES FROM 1ST JAN,2022 TO 10TH MARCH,2023

date=pd.date_range(start='1-1-2022', end='10-3-2023')
st=pd.Series(date)
print(date)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2023-09-24', '2023-09-25', '2023-09-26', '2023-09-27',
               '2023-09-28', '2023-09-29', '2023-09-30', '2023-10-01',
               '2023-10-02', '2023-10-03'],
              dtype='datetime64[ns]', length=641, freq='D')


In [27]:
# 10.CREATE A 2D LIST TO DATAFRAME

lists=[[1,'aaa',11],[2,'bbb',22],[3,'ccc',33]]
df=pd.DataFrame(lists,columns=['c1','c2','c3'])
print(df)

   c1   c2  c3
0   1  aaa  11
1   2  bbb  22
2   3  ccc  33
